apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-calculator
  labels:
    app: mortgage-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-calculator
  template:
    metadata:
      labels:
        app: mortgage-calculator
    spec:
      containers:
      - name: mortgage-calculator
        image: registry.digitalocean.com/dugan-docker-registry/mortgage-calculator-image:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mortgage-calculator-service
  labels:
    app: mortgage-calculator
spec:
  type: LoadBalancer
  selector:
    app: mortgage-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31234